name: Deploy Backend to Cloud Run

on:
  push:
    branches:
      - feature/MDP-41-despliegue-de-backend
      - developer

env:
  PROJECT_ID: 'mesa-de-partes-501300 ' # REEMPLAZA ESTO
  REGION: 'us-central1'
  SERVICE_NAME: 'todo-app-backend'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      # Autenticarse con Google Cloud usando el secreto
      - name: Autenticación en Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      # Configurar el SDK de Google Cloud
      - name: Configurar Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      # Enviar el código directamente a Cloud Build y Cloud Run
      # gcloud lee tu Dockerfile multi-stage, construye la imagen optimizada en la nube y la despliega
      - name: Construir y Desplegar en Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --source ./backend \
            --region ${{ env.REGION }} \
            --port 8000 \
            --allow-unauthenticated \
            --project ${{ env.PROJECT_ID }}
